name: risda_driver_app
description: "RISDA Driver Application - Clean Architecture"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # API & Network
  dio: ^5.4.0
  connectivity_plus: ^4.0.2
  
  # Local Storage (Offline Support)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Utilities
  uuid: ^4.3.3
  
  # Device Features
  geolocator: ^10.1.0
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  
  # State Management (lightweight)
  provider: ^6.1.1
  
  # Date formatting
  intl: ^0.19.0
  
  # Charts
  fl_chart: ^0.69.0
  
  # Firebase (Push Notifications)
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  
  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logojara.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/splashscreen.png
    - assets/risda.png
    - assets/logojara.png
    - assets/risdalogo.png
    - assets/background-landscape.png
    - assets/background-potrait.png
    - assets/splash.gif
    - assets/login.gif
    - assets/login-potrait.gif
    - assets/splash-backup.gif